spriteSet = {'Cloud','Sun','Dice','Pumpkin','Bone','Chocolate',...
    'Glove','Bag','Rug','Football','Glass','Fan',...
    'Box','Book','Heart','Lemon','Pear','Kiwi','Mirror', ...
    'Text'};
valueSet = [1:19, 10000];

SpritesReverse = containers.Map(valueSet,spriteSet);
clear valueSet spriteSet