valueSet = [1:19, 10001:10019, 30001:30004, 30007:30009, 40001];
textureSet = {'normal_cloud.png','normal_sun.png','normal_dice.png','normal_pumpkin.png','normal_bone.png','normal_chocolate.png',...
              'normal_glove.png','normal_bag.png','normal_rug.png','normal_football.png','normal_glass.png','normal_fan.png',...
              'normal_box.png','normal_book.png','normal_heart.png','normal_lemon.png','normal_pear.png','normal_kiwi.png','normal_mirror.png',...
              'rule_cloud.png','rule_sun.png','rule_dice.png','rule_pumpkin.png','rule_bone.png','rule_chocolate.png',...
              'rule_glove.png','rule_bag.png','rule_rug.png','rule_football.png','rule_glass.png','rule_fan.png',...
              'rule_box.png','rule_book.png','rule_heart.png','rule_lemon.png','rule_pear.png','rule_kiwi.png','rule_mirror.png',...
              'attribute_push.png','attribute_you.png','attribute_win.png','attribute_stop.png','attribute_defeat.png','attribute_melt.png','attribute_hot.png','keyword_is.png'};
Textures = containers.Map(valueSet, textureSet);

clear valueSet textureSet