function p = plotObstacleGrid(graphLattice)
      y_max = max(graphLattice.Nodes.ypos);
      p = plot(graphLattice, 'Marker', 'none', ...
              'XData', graphLattice.Nodes.xpos - 0.5, ...
              'YData', y_max - graphLattice.Nodes.ypos + 0.5, ...
              'EdgeColor', [0.5 0.5 0.5], ...
              'LineWidth', 1.25, ...
              'NodeColor', [0.5 0.5 0.5]);
end